### ISSUE TITLE
Issue with LineHistory() and multiple participants

### ISSUE THREAD

**Issue by Justin-Wise** [JeMorriso/PySBR#1]
When I run:
`ol = LineHistory(max(e.ids()), ncaab.market_ids('ps')[0], sb.ids('Bovada')[0],[baylor[0],gonzaga[0]])`
`print(ol.dataframe())`

I only get the dataframe for Gonzaga line history, and not both. Should the function be able to accept a list of Team IDs and return a full line history with both teams?

**Comment by JeMorriso** [comment]
Yes, you are correct it should be able to get line histories for both teams in the game. I will investigate this and get back to you. Thanks for posting

**Comment by JeMorriso** [comment]
Fixed and released to PyPI as part of version 0.2.0.
