### ISSUE TITLE
HTTPError: 463 Client Error

### ISSUE THREAD

**Issue by fishyfishwhale** [JeMorriso/PySBR#5]
I've used this package in the past with success. But now I try running EventsByDateRange and get the following error:

HTTPError: 463 Client Error:  for url: https://www.sportsbookreview.com/ms-odds-v2/odds-v2-service

Any idea what happened here? Did I get my IP banned...

**Comment by JeMorriso** [comment]
Fixed!

**Comment by JeMorriso** [comment]
Update to version 0.3.1
